# Generated by Django 6.0.6 on 2026-06-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='content',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='title',
            new_name='description',
        ),
    ]
