# Generated by Django 6.0.6 on 2026-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Fruits & Vegetables', max_length=200)),
                ('discount_percent', models.PositiveIntegerField(help_text='Masalan: 20 (foiz belgisisiz)')),
                ('image', models.ImageField(upload_to='promotions/')),
                ('link', models.CharField(blank=True, default='#', help_text='Shop Collection havolasi', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Chiqish tartibi (kichik raqam birinchi)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
