# Generated by Django 6.0.6 on 2026-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
